/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.util.ArrayList;
import modele.*;
import controleur.*;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.*;
import javax.swing.*;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author comel
 */
public class Home extends javax.swing.JFrame {

    private Connexion connect;
    private Chambre chambre;
    private Service service;
    private DefaultTableModel model_chambre; 
    private DefaultTableModel model_service; 
    private String requete_sql; 
    

    /**
     * Creates new form Test
     *
     * @param con
     */
    public Home(Connexion con) {
        initComponents();
        connect = con;
        chambre = new Chambre(con);
        service = new Service(con);
        requete_sql = "SELECT * FROM chambre;";
        model_chambre = (DefaultTableModel) jTable1.getModel();
        model_service = (DefaultTableModel) jTable_service.getModel();
        centrerTable(jTable1);
        centrerTable(jTable_service);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(new ButtonRenderer());
        jTable1.getColumnModel().getColumn(5).setCellRenderer(new ButtonRenderer());
        jTable_service.getColumnModel().getColumn(4).setCellRenderer(new ButtonRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        choice1 = new java.awt.Choice();
        rechercher = new java.awt.TextField();
        button_acceuil = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        button_malades = new javax.swing.JButton();
        button_employes = new javax.swing.JButton();
        button_chambres = new javax.swing.JButton();
        button_services = new javax.swing.JButton();
        main_panel = new javax.swing.JPanel();
        home_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        chambre_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        recherche_chambre = new javax.swing.JTextField();
        categorie_chambre = new java.awt.Choice();
        button_ch_search = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        service_panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_service = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        recherche_service = new javax.swing.JTextField();
        categorie_service = new java.awt.Choice();
        button_se_search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("main_frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1700, 800));

        jPanel1.setBackground(new java.awt.Color(255, 66, 7));
        jPanel1.setPreferredSize(new java.awt.Dimension(1700, 70));

        choice1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        choice1.setName("Categories"); // NOI18N
        choice1.setPreferredSize(new java.awt.Dimension(85, 40));

        rechercher.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        rechercher.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        rechercher.setPreferredSize(new java.awt.Dimension(85, 35));
        rechercher.setText("Recherche...");
        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });

        button_acceuil.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        button_acceuil.setText("Accueil");
        button_acceuil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_acceuilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_acceuil)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_acceuil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
<<<<<<< HEAD
<<<<<<< HEAD
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(choice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
=======
=======
>>>>>>> 0743c2253783774827fdad199216afc28d794076
                .addGap(19, 19, 19)
                .addComponent(rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(button_acceuil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
>>>>>>> 0743c2253783774827fdad199216afc28d794076
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 730));

        button_malades.setBackground(new java.awt.Color(255, 255, 255));
        button_malades.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_malades.setText("Malades");
        button_malades.setPreferredSize(new java.awt.Dimension(100, 40));

        button_employes.setBackground(new java.awt.Color(255, 255, 255));
        button_employes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_employes.setText("Employés");
        button_employes.setPreferredSize(new java.awt.Dimension(100, 40));

        button_chambres.setBackground(new java.awt.Color(255, 255, 255));
        button_chambres.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_chambres.setText("Chambres");
        button_chambres.setPreferredSize(new java.awt.Dimension(100, 40));
        button_chambres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_chambresMouseClicked(evt);
            }
        });

        button_services.setBackground(new java.awt.Color(255, 255, 255));
        button_services.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_services.setText("Services");
        button_services.setPreferredSize(new java.awt.Dimension(100, 40));
        button_services.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_servicesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(button_chambres, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_employes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_malades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_services, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button_chambres, button_employes, button_malades, button_services});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(button_services, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_chambres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_employes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_malades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {button_chambres, button_employes, button_malades, button_services});

        main_panel.setLayout(new java.awt.CardLayout());

        home_panel.setBackground(new java.awt.Color(50, 102, 145));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 180, 15));
        jLabel2.setText("Bienvenue dans la base de données du service");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/ressoucres/hopital.png"))); // NOI18N

        javax.swing.GroupLayout home_panelLayout = new javax.swing.GroupLayout(home_panel);
        home_panel.setLayout(home_panelLayout);
        home_panelLayout.setHorizontalGroup(
            home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_panelLayout.createSequentialGroup()
<<<<<<< HEAD
<<<<<<< HEAD
                .addGap(629, 629, 629)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_panelLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(208, 208, 208))
=======
=======
>>>>>>> 0743c2253783774827fdad199216afc28d794076
                .addContainerGap(215, Short.MAX_VALUE)
                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_panelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(576, 576, 576))))
<<<<<<< HEAD
>>>>>>> 0743c2253783774827fdad199216afc28d794076
=======
>>>>>>> 0743c2253783774827fdad199216afc28d794076
        );
        home_panelLayout.setVerticalGroup(
            home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_panelLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel2)
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
<<<<<<< HEAD
<<<<<<< HEAD
                .addContainerGap(289, Short.MAX_VALUE))
=======
                .addContainerGap(340, Short.MAX_VALUE))
>>>>>>> 0743c2253783774827fdad199216afc28d794076
=======
                .addContainerGap(340, Short.MAX_VALUE))
>>>>>>> 0743c2253783774827fdad199216afc28d794076
        );

        main_panel.add(home_panel, "card3");

        chambre_panel.setBackground(new java.awt.Color(50, 102, 145));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 180, 15));
        jLabel3.setText("Chambres");

        recherche_chambre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        recherche_chambre.setText("Rechercher...");
        recherche_chambre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recherche_chambreMouseClicked(evt);
            }
        });

        categorie_chambre.add("no_chambre");
        categorie_chambre.add("code_service");
        categorie_chambre.add("surveillant");
        categorie_chambre.add("nb_lits");
        categorie_chambre.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        button_ch_search.setText("Go");
        button_ch_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_ch_searchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(recherche_chambre, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(categorie_chambre, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(button_ch_search)
                .addContainerGap(543, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_ch_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recherche_chambre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(categorie_chambre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTable1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code du service", "Numéro", "Surveillant", "Nombre de lits", "Modifier", "Supprimer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(50);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
<<<<<<< HEAD
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
=======
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
>>>>>>> 0743c2253783774827fdad199216afc28d794076
=======
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
>>>>>>> 0743c2253783774827fdad199216afc28d794076
        );

        javax.swing.GroupLayout chambre_panelLayout = new javax.swing.GroupLayout(chambre_panel);
        chambre_panel.setLayout(chambre_panelLayout);
        chambre_panelLayout.setHorizontalGroup(
            chambre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chambre_panelLayout.createSequentialGroup()
                .addGroup(chambre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chambre_panelLayout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(jLabel3))
                    .addGroup(chambre_panelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(chambre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
<<<<<<< HEAD
<<<<<<< HEAD
                .addContainerGap(40, Short.MAX_VALUE))
=======
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> 0743c2253783774827fdad199216afc28d794076
=======
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> 0743c2253783774827fdad199216afc28d794076
        );
        chambre_panelLayout.setVerticalGroup(
            chambre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chambre_panelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_panel.add(chambre_panel, "card2");

        service_panel.setBackground(new java.awt.Color(50, 102, 145));

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 180, 15));
        jLabel4.setText("Services");

        jTable_service.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable_service.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Code", "Batiment", "Directeur", "Modifier"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_service.setToolTipText("");
        jTable_service.setRowHeight(45);
        jTable_service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_serviceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_service);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        recherche_service.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        recherche_service.setText("Rechercher...");
        recherche_service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recherche_serviceMouseClicked(evt);
            }
        });

        categorie_service.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        categorie_service.add("code");
        categorie_service.add("nom");
        categorie_service.add("batiment");
        categorie_service.add("directeur");

        button_se_search.setText("Go");
        button_se_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_se_searchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(recherche_service, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(categorie_service, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
<<<<<<< HEAD
                .addComponent(button_se_search)
                .addContainerGap(456, Short.MAX_VALUE))
=======
                .addComponent(jButton2)
                .addContainerGap(442, Short.MAX_VALUE))
<<<<<<< HEAD
>>>>>>> 0743c2253783774827fdad199216afc28d794076
=======
>>>>>>> 0743c2253783774827fdad199216afc28d794076
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(button_se_search, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(recherche_service, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categorie_service, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout service_panelLayout = new javax.swing.GroupLayout(service_panel);
        service_panel.setLayout(service_panelLayout);
        service_panelLayout.setHorizontalGroup(
            service_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(service_panelLayout.createSequentialGroup()
                .addGroup(service_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(service_panelLayout.createSequentialGroup()
                        .addGap(611, 611, 611)
                        .addComponent(jLabel4))
                    .addGroup(service_panelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(service_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(126, 126, 126))
        );
        service_panelLayout.setVerticalGroup(
            service_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(service_panelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_panel.add(service_panel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
<<<<<<< HEAD
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
=======
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1704, Short.MAX_VALUE)
>>>>>>> 0743c2253783774827fdad199216afc28d794076
=======
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1704, Short.MAX_VALUE)
>>>>>>> 0743c2253783774827fdad199216afc28d794076
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
<<<<<<< HEAD
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
=======
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
>>>>>>> 0743c2253783774827fdad199216afc28d794076
=======
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
>>>>>>> 0743c2253783774827fdad199216afc28d794076
                    .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercherActionPerformed

    private void button_chambresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_chambresMouseClicked
        main_panel.removeAll();
        ini_tableau_chambre(chambre.actualiser(connect));
        main_panel.add(chambre_panel);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_button_chambresMouseClicked

    private void button_acceuilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_acceuilMouseClicked
        main_panel.removeAll();
        main_panel.add(home_panel);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_button_acceuilMouseClicked

    private void button_servicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_servicesMouseClicked
        // TODO add your handling code here:
        main_panel.removeAll();
        ini_tableau_service(service.actualiser(connect));
        main_panel.add(service_panel);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_button_servicesMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        remplir_jTable(evt, jTable1, model_chambre);
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void recherche_chambreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recherche_chambreMouseClicked
        recherche_chambre.setText("");
    }//GEN-LAST:event_recherche_chambreMouseClicked

    private void button_ch_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ch_searchMouseClicked
        requete_sql = "SELECT * FROM chambre WHERE " + categorie_chambre.getSelectedItem() + " LIKE '%" + recherche_chambre.getText() +"%';";
        chambre.result = chambre.recherche(connect, requete_sql); 
        System.out.println(requete_sql);
        ini_tableau_chambre(chambre.result);
    }//GEN-LAST:event_button_ch_searchMouseClicked

    private void jTable_serviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_serviceMouseClicked
        // TODO add your handling code here:
        remplir_jTable(evt, jTable_service, model_service);
        
    }//GEN-LAST:event_jTable_serviceMouseClicked

    private void button_se_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_se_searchMouseClicked
        requete_sql = "SELECT * FROM service WHERE " + categorie_service.getSelectedItem() + " LIKE '%" + recherche_service.getText() +"%';";
        service.result = service.recherche(connect, requete_sql); 
        ini_tableau_service(service.result);
    }//GEN-LAST:event_button_se_searchMouseClicked

    private void recherche_serviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recherche_serviceMouseClicked
        recherche_service.setText("");
    }//GEN-LAST:event_recherche_serviceMouseClicked
 
    private void ini_tableau_chambre(Vector<Vector> requete) {
        ini_tableau(model_chambre, jTable1, requete);
    }
    
    private void ini_tableau_service(Vector<Vector> requete) {
        ini_tableau(model_service, jTable_service, requete);
    }
    
    private void ini_tableau(DefaultTableModel model, JTable table, Vector<Vector> requete) {
        while (model.getRowCount() != 0) {
            model.removeRow(0);
        } 
        JButton modifier = new JButton("modifier");
        JButton supprimer = new JButton("supprimer");
        modifier.setName("m");
        supprimer.setName("s");
        for (int i = 0; i < requete.size(); i++) {
            Vector data = requete.get(i);     
            data.add(modifier);
            data.add(supprimer);
            model.addRow(data);
        }
        table.repaint();
        table.revalidate();
    }
    
    private void remplir_jTable(java.awt.event.MouseEvent evt, JTable table, DefaultTableModel model) {
        int column = table.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/table.getRowHeight();
        if (row < table.getRowCount() && row>=0 && column < table.getColumnCount() && column >=0) {
            Object value = table.getValueAt(row, column);
            if(value instanceof JButton) {
                ((JButton)value).doClick();
                JButton bouton = (JButton)value;
                
                if (bouton.getName().equals("m")) {
                    ArrayList<String> valeur_ligne = new ArrayList<String>();
                    for (int i=0; i<table.getColumnCount()-2; i++) {
                        valeur_ligne.add(table.getValueAt(row, i).toString());
                    }
                    if (table == jTable1) {
                        popup_modifier_chambre(model_chambre, valeur_ligne); 
                    }
                    if (table == jTable_service) {
                        
                    }
                }
                if (bouton.getName().equals("s")) {
                    int h = JOptionPane.showConfirmDialog(null, "Etes vous sûr de vouloir supprimer cet élément ?", "supprimer", 0);
                    if (h==0) {
                        System.out.println("00000000000");
                        //comande de suppression SQL
                        
                    } else {
                        //on ne fait rien
                    }
                }
            } 
        }
    }

    private void popup_modifier_chambre(DefaultTableModel model, ArrayList valeur_ligne) {
        JTextField code_service = new JTextField(valeur_ligne.get(0).toString());
        JTextField num_chambre = new JTextField(valeur_ligne.get(1).toString());
        JTextField surveillant = new JTextField(valeur_ligne.get(2).toString());
        JTextField nb_lits = new JTextField(valeur_ligne.get(3).toString());
        Object[] message = {
            "Code du service", code_service,
            "Numéro de chambre", num_chambre,
            "Surveillant", surveillant,
            "Nombre de lits", nb_lits
        };
        int option = JOptionPane.showConfirmDialog(null, message, "modifier", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            String requete = "UPDATE chambre SET "
                    + "code_service = '" + code_service.getText() + "', "
                    + "no_chambre = '" + num_chambre.getText() + "', "
                    + "surveillant = '" + surveillant.getText() + "', "
                    + "nb_lits = '" + nb_lits.getText() + "' "
                    + "WHERE code_service = '" + valeur_ligne.get(0).toString() + "' AND no_chambre = '" + valeur_ligne.get(1).toString() + "';";
            chambre.modifier(connect, requete);
            ini_tableau_chambre(chambre.actualiser(connect));
        } else {
            
        }
    }
    
    private void centrerTable(JTable table) {
        DefaultTableCellRenderer custom = new DefaultTableCellRenderer();
        custom.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(custom);
        }
    }
    
    class ButtonRenderer extends JButton implements TableCellRenderer {

        public ButtonRenderer() {
            setOpaque(true);
        }

        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            if (isSelected) {
                setForeground(table.getSelectionForeground());
                setBackground(table.getSelectionBackground());
            } else {
                setForeground(table.getForeground());
                setBackground(UIManager.getColor("Button.background"));
            }
            if (value instanceof JButton) {
                return (JButton) value;
            } else {
                return this;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_acceuil;
    private javax.swing.JButton button_ch_search;
    private javax.swing.JButton button_chambres;
    private javax.swing.JButton button_employes;
    private javax.swing.JButton button_malades;
    private javax.swing.JButton button_se_search;
    private javax.swing.JButton button_services;
    private java.awt.Choice categorie_chambre;
    private java.awt.Choice categorie_service;
    private javax.swing.JPanel chambre_panel;
    private java.awt.Choice choice1;
    private javax.swing.JPanel home_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_service;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField recherche_chambre;
    private javax.swing.JTextField recherche_service;
    private java.awt.TextField rechercher;
    private javax.swing.JPanel service_panel;
    // End of variables declaration//GEN-END:variables
}
